export const stickerCategories = [
  {
    category: 'Couple',
    stickers: [
      require('../assets/images/Couple/c1-removebg-preview.png'),
      require('../assets/images/Couple/c2-removebg-preview.png'),
      require('../assets/images/Couple/c3-removebg-preview.png'),
      require('../assets/images/Couple/c4-removebg-preview.png'),
      require('../assets/images/Couple/c5-removebg-preview.png'),
      require('../assets/images/Couple/c6-removebg-preview.png'),
      require('../assets/images/Couple/c7-removebg-preview.png'),
      require('../assets/images/Couple/c8-removebg-preview.png'),
      require('../assets/images/Couple/c10-removebg-preview.png'),
    
    ],
  },
  {
    category: 'Mood',
    stickers: [
      require('../assets/mood stickers/mood1.png'),
      require('../assets/mood stickers/mood2.png'),
      require('../assets/mood stickers/mood3.png'),
      require('../assets/mood stickers/mood4-removebg-preview.png'),
      require('../assets/mood stickers/mood5-removebg-preview.png'),
      require('../assets/mood stickers/mood_6-removebg-preview.png'),
      require('../assets/mood stickers/mood_7-removebg-preview.png'),
      require('../assets/mood stickers/mood8-removebg-preview.png'),
      require('../assets/mood stickers/mood9-removebg-preview.png'),
      require('../assets/mood stickers/mood10-removebg-preview (1).png'),
      require('../assets/mood stickers/mood11-removebg-preview.png'),
      require('../assets/mood stickers/mood_12-removebg-preview.png'),
      require('../assets/mood stickers/mood_13-removebg-preview.png'),
    ],
  },
    {
    category: 'Animal',
    stickers: [
      require('../assets/AnimalSticker/e1.png'),
      require('../assets/AnimalSticker/e2.png'),
      require('../assets/AnimalSticker/e3.png'),
      require('../assets/AnimalSticker/e4.png'),
      require('../assets/AnimalSticker/e5.png'),
      require('../assets/AnimalSticker/e6.png'),
      require('../assets/AnimalSticker/e7.png'),
      require('../assets/AnimalSticker/e8.png'),
      require('../assets/AnimalSticker/e9.png'),
      require('../assets/AnimalSticker/e10.png'),
      require('../assets/AnimalSticker/e11.png'),
      require('../assets/AnimalSticker/e12.png'),
      require('../assets/AnimalSticker/e13.png'),
      require('../assets/AnimalSticker/e14.png'),
      require('../assets/AnimalSticker/e15.png'),
      require('../assets/AnimalSticker/e16.png'),
    ],
  },
    {
    category: 'Nature',
    stickers: [
      require('../assets/Nautre/n1.png'),
      require('../assets/Nautre/n2.png'),
      require('../assets/Nautre/n3.png'),
      require('../assets/Nautre/n4.png'),
      require('../assets/Nautre/n5.png'),
      require('../assets/Nautre/n6.png'),
      require('../assets/Nautre/n7.png'),
      require('../assets/Nautre/n8.png'),
      require('../assets/Nautre/n9.png'),
      require('../assets/Nautre/n10.png'),
      require('../assets/Nautre/n11.png'),
      require('../assets/Nautre/n12.png'),
      require('../assets/Nautre/n13.png'),
      require('../assets/Nautre/n14.png'),
      require('../assets/Nautre/n15.png'),
      require('../assets/Nautre/n16.png'),
      require('../assets/Nautre/n17.png'),
      
    ],
  },
    {
    category: 'Abstract',
    stickers: [
      require('../assets/Shapes/a1.png'),
      require('../assets/Shapes/a2.png'),
      require('../assets/Shapes/a3.png'),
      require('../assets/Shapes/a4.png'),
      require('../assets/Shapes/a5.png'),
      require('../assets/Shapes/a6.png'),
      require('../assets/Shapes/a7.png'),
      require('../assets/Shapes/a8.png'),
      require('../assets/Shapes/a9.png'),
      require('../assets/Shapes/a10.png'),
      require('../assets/Shapes/a11.png'),
      require('../assets/Shapes/a12.png'),
      require('../assets/Shapes/a13.png'),
      require('../assets/Shapes/a14.png'),
      require('../assets/Shapes/a15.png'),
      
    ],
  },
    {
    category: 'Foods',
    stickers: [
      require('../assets/Food/d1.png'),
      require('../assets/Food/d2.png'),
      require('../assets/Food/d3.png'),
      require('../assets/Food/d4.png'),
      require('../assets/Food/d5.png'),
      require('../assets/Food/d6.png'),
      require('../assets/Food/d7.png'),
      require('../assets/Food/d8.png'),
      require('../assets/Food/d9.png'),
      require('../assets/Food/d10.png'),
      require('../assets/Food/d11.png'),
      require('../assets/Food/d12.png'),
      require('../assets/Food/d13.png'),
      require('../assets/Food/d14.png'),
      require('../assets/Food/d15.png'),
    ],
  },
];
